// Pure shared-content decoders: JSON enters as unknown and is checked before use.
export function objectValue(value: unknown, path: string): Record<string, unknown> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${path}: expected an object`)
  return value as Record<string, unknown>
}

export function stringValue(value: unknown, path: string): string {
  if (typeof value !== 'string' || !value.trim()) throw new Error(`${path}: expected a non-empty string`)
  return value
}

export function numberValue(value: unknown, path: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) throw new Error(`${path}: expected a finite number`)
  return value
}

export function listValue<T>(value: unknown, path: string, decode: (value: unknown, path: string) => T): T[] {
  if (!Array.isArray(value)) throw new Error(`${path}: expected an array`)
  return value.map((item: unknown, index) => decode(item, `${path}[${index}]`))
}

export function optionalString(value: unknown, path: string): string | undefined {
  return value === undefined ? undefined : stringValue(value, path)
}

function uniqueIds<T extends { id: string }>(items: T[], path: string): T[] {
  if (new Set(items.map(item => item.id)).size !== items.length) throw new Error(`${path}: duplicate IDs`)
  return items
}

function sectionValue(value: unknown, path: string) {
  const item = objectValue(value, path)
  return { id: stringValue(item.id, `${path}.id`), label: stringValue(item.label, `${path}.label`),
    title: stringValue(item.title, `${path}.title`), description: stringValue(item.description, `${path}.description`) }
}

function linkValue(value: unknown, path: string) {
  const item = objectValue(value, path)
  return { id: stringValue(item.id, `${path}.id`), label: stringValue(item.label, `${path}.label`), href: stringValue(item.href, `${path}.href`) }
}

function journeyValue(value: unknown, path: string) {
  const item = objectValue(value, path)
  const category = stringValue(item.category, `${path}.category`)
  const common = { id: stringValue(item.id, `${path}.id`), title: stringValue(item.title, `${path}.title`),
    organization: stringValue(item.organization, `${path}.organization`), period: stringValue(item.period, `${path}.period`),
    description: stringValue(item.description, `${path}.description`),
    ...(item.displayTitle === undefined ? {} : { displayTitle: stringValue(item.displayTitle, `${path}.displayTitle`) }),
    ...(item.cardTitle === undefined ? {} : { cardTitle: stringValue(item.cardTitle, `${path}.cardTitle`) }),
    ...(item.cardHeading === undefined ? {} : { cardHeading: stringValue(item.cardHeading, `${path}.cardHeading`) }),
    ...(item.cardSpecialism === undefined ? {} : { cardSpecialism: stringValue(item.cardSpecialism, `${path}.cardSpecialism`) }) }
  if (category === 'EXPERIENCE') return { ...common, category: 'EXPERIENCE' as const, highlights: listValue(item.highlights, `${path}.highlights`, stringValue) }
  if (category === 'EDUCATION') return { ...common, category: 'EDUCATION' as const }
  throw new Error(`${path}.category: expected EXPERIENCE or EDUCATION`)
}

export function parsePortfolio(value: unknown) {
  const data = objectValue(value, 'portfolio')
  const music = objectValue(data.music, 'portfolio.music')
  const hero = objectValue(data.hero, 'portfolio.hero')
  const action = objectValue(hero.action, 'portfolio.hero.action')
  const about = objectValue(data.about, 'portfolio.about')
  const profile = objectValue(about.profile, 'portfolio.about.profile')
  const portrait = objectValue(profile.portrait, 'portfolio.about.profile.portrait')
  for (const field of ['src', 'originalSrc', 'cellSize']) {
    if (field in portrait) throw new Error(`portfolio.about.profile.portrait.${field}: generated by the portrait manifest`)
  }
  const skills = objectValue(data.skills, 'portfolio.skills')
  const projects = objectValue(data.projects, 'portfolio.projects')
  const journey = objectValue(data.journey, 'portfolio.journey')
  const contact = objectValue(data.contact, 'portfolio.contact')
  const volume = numberValue(music.volume, 'portfolio.music.volume')
  if (volume < 0 || volume > 1) throw new Error('portfolio.music.volume: expected 0–1')
  const contactLinks = uniqueIds(listValue(contact.links, 'portfolio.contact.links', linkValue), 'portfolio.contact.links')
  for (const id of ['email', 'phone', 'whatsapp', 'github']) {
    if (!contactLinks.some(link => link.id === id)) throw new Error(`portfolio.contact.links: missing ${id}`)
  }
  return {
    name: stringValue(data.name, 'portfolio.name'), fullName: stringValue(data.fullName, 'portfolio.fullName'), siteTitle: stringValue(data.siteTitle, 'portfolio.siteTitle'),
    music: { title: stringValue(music.title, 'portfolio.music.title'), artist: stringValue(music.artist, 'portfolio.music.artist'),
      src: stringValue(music.src, 'portfolio.music.src'), volume, source: stringValue(music.source, 'portfolio.music.source') },
    hero: { label: stringValue(hero.label, 'portfolio.hero.label'), headline: stringValue(hero.headline, 'portfolio.hero.headline'),
      introduction: stringValue(hero.introduction, 'portfolio.hero.introduction'),
      action: { label: stringValue(action.label, 'portfolio.hero.action.label'), href: stringValue(action.href, 'portfolio.hero.action.href') } },
    about: { ...sectionValue(about, 'portfolio.about'), profile: {
      role: stringValue(profile.role, 'portfolio.about.profile.role'), status: stringValue(profile.status, 'portfolio.about.profile.status'),
      location: stringValue(profile.location, 'portfolio.about.profile.location'), focus: stringValue(profile.focus, 'portfolio.about.profile.focus'),
      approach: stringValue(profile.approach, 'portfolio.about.profile.approach'), revision: stringValue(profile.revision, 'portfolio.about.profile.revision'),
      stack: listValue(profile.stack, 'portfolio.about.profile.stack', stringValue), strengths: listValue(profile.strengths, 'portfolio.about.profile.strengths', stringValue),
      interests: listValue(profile.interests, 'portfolio.about.profile.interests', stringValue),
      portrait: { alt: stringValue(portrait.alt, 'portfolio.about.profile.portrait.alt'), caption: stringValue(portrait.caption, 'portfolio.about.profile.portrait.caption') }
    } },
    skills: { ...sectionValue(skills, 'portfolio.skills'), learning: listValue(skills.learning, 'portfolio.skills.learning', stringValue),
      groups: uniqueIds(listValue(skills.groups, 'portfolio.skills.groups', (value, path) => {
        const group = objectValue(value, path)
        return { id: stringValue(group.id, `${path}.id`), title: stringValue(group.title, `${path}.title`), items: listValue(group.items, `${path}.items`, stringValue) }
      }), 'portfolio.skills.groups') },
    projects: { ...sectionValue(projects, 'portfolio.projects'), items: uniqueIds(listValue(projects.items, 'portfolio.projects.items', (value, path) => {
      const project = objectValue(value, path)
      return { id: stringValue(project.id, `${path}.id`), title: stringValue(project.title, `${path}.title`), status: stringValue(project.status, `${path}.status`),
        description: stringValue(project.description, `${path}.description`), technologies: listValue(project.technologies, `${path}.technologies`, stringValue),
        links: uniqueIds(listValue(project.links, `${path}.links`, linkValue), `${path}.links`) }
    }), 'portfolio.projects.items') },
    journey: { ...sectionValue(journey, 'portfolio.journey'), items: uniqueIds(listValue(journey.items, 'portfolio.journey.items', journeyValue), 'portfolio.journey.items') },
    contact: { ...sectionValue(contact, 'portfolio.contact'), email: stringValue(contact.email, 'portfolio.contact.email'), phone: stringValue(contact.phone, 'portfolio.contact.phone'), links: contactLinks }
  }
}

export type PortfolioContent = ReturnType<typeof parsePortfolio>
export type JourneyRecord = PortfolioContent['journey']['items'][number]

export function parsePortraitManifest(value: unknown) {
  const data = objectValue(value, 'portrait manifest')
  const cellSize = numberValue(data.cellSize, 'portrait manifest.cellSize')
  if (cellSize <= 0) throw new Error('portrait manifest.cellSize: expected a positive number')
  const originalImage = optionalString(data.originalImage, 'portrait manifest.originalImage')
  return { image: stringValue(data.image, 'portrait manifest.image'), assetHash: stringValue(data.assetHash, 'portrait manifest.assetHash'), cellSize,
    ...(originalImage ? { originalImage, originalAssetHash: stringValue(data.originalAssetHash, 'portrait manifest.originalAssetHash') } : {}) }
}

export type Portfolio = Omit<PortfolioContent, 'about'> & {
  about: Omit<PortfolioContent['about'], 'profile'> & {
    profile: Omit<PortfolioContent['about']['profile'], 'portrait'> & {
      portrait: PortfolioContent['about']['profile']['portrait'] & { src: string; originalSrc: string | null; cellSize: number }
    }
  }
}

export interface CaseSection { heading: string; markdown: string }
export interface SiteLink { url: string; label: string }
export interface RepositoryLink { id: string; title: string; url: string }
export interface PublicCaseContent {
  catalogueSections?: CaseSection[]
  repositoryLinksRestricted?: boolean
  repositories?: { url: string }[]
  url?: string | null
  siteLinks?: SiteLink[]
  liveUrl?: string
  liveLabel?: string
}

export function parseCaseSections(value: unknown, path: string): CaseSection[] {
  return listValue(value, path, (value, path) => {
    const section = objectValue(value, path)
    return { heading: stringValue(section.heading, `${path}.heading`), markdown: stringValue(section.markdown, `${path}.markdown`) }
  })
}

// Only shared catalogue content is decoded here; scene/navigation types are separate.
export function parseProjectCatalogue(value: unknown) {
  const data = objectValue(value, 'project catalogue')
  return uniqueIds(listValue(data.projects, 'project catalogue.projects', (value, path) => {
    const project = objectValue(value, path)
    const repositories = project.repositories === undefined ? [] : listValue(project.repositories, `${path}.repositories`, (value, path): RepositoryLink => {
      const repository = objectValue(value, path)
      return { id: stringValue(repository.id, `${path}.id`), title: stringValue(repository.title, `${path}.title`), url: stringValue(repository.url, `${path}.url`) }
    })
    return { id: stringValue(project.id, `${path}.id`), title: stringValue(project.title, `${path}.title`), overview: stringValue(project.overview, `${path}.overview`),
      tags: listValue(project.tags, `${path}.tags`, stringValue), repositories,
      catalogueTitle: optionalString(project.catalogueTitle, `${path}.catalogueTitle`), liveUrl: optionalString(project.liveUrl, `${path}.liveUrl`),
      liveStatus: optionalString(project.liveStatus, `${path}.liveStatus`), liveNote: optionalString(project.liveNote, `${path}.liveNote`) }
  }), 'project catalogue.projects')
}

export function parseMediaManifest(value: unknown) {
  const data = objectValue(value, 'media manifest')
  if (data.version !== 1) throw new Error('media manifest.version: expected 1')
  const files = objectValue(data.files, 'media manifest.files')
  return { version: 1, files: Object.fromEntries(Object.entries(files).map(([id, value]) => {
    const path = `media manifest.files.${id}`
    const asset = objectValue(value, path)
    const sha256 = stringValue(asset.sha256, `${path}.sha256`)
    if (!/^[a-f0-9]{64}$/.test(sha256)) throw new Error(`${path}.sha256: expected a SHA-256 digest`)
    return [id, { source: stringValue(asset.source, `${path}.source`), sha256, publicPath: optionalString(asset.publicPath, `${path}.publicPath`),
      legacyPaths: listValue(asset.legacyPaths, `${path}.legacyPaths`, stringValue) }] as const
  })) }
}
