import assert from 'node:assert/strict'
import { preview } from 'vite'
import { chromium, chromeExecutable, installBrowserHelpers, screenshotPath } from './browser_tools.mts'
import { jsonFile } from './node_json.mts'
import { parseCv } from '../src/types/cv.ts'

const cv = parseCv(jsonFile(new URL('../src/data/cv.json', import.meta.url)))

const server = await preview({ preview: { host: '127.0.0.1', port: 0 } })
let browser
try {
  browser = await chromium.launch({ executablePath: chromeExecutable, headless: true, args: ['--no-sandbox', '--enable-unsafe-swiftshader', '--use-gl=angle', '--use-angle=swiftshader'] })
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce', permissions: ['clipboard-read', 'clipboard-write'] })
  await installBrowserHelpers(context, () => {
    localStorage.setItem('damien-portfolio:audio-consent', 'muted')
    localStorage.setItem('damien-portfolio:room-menu:01', 'expanded')
  })
  const page = await context.newPage()
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const address = server.httpServer.address()
  assert.ok(address && typeof address !== 'string')
  await page.goto(`http://127.0.0.1:${address.port}/damien-portfolio/?mode=3d`)
  await page.locator('.city-stage[data-loaded="true"]').waitFor({ timeout: 120000 })
  await page.getByRole('button', { name: /^Choose a floor/ }).click()
  await page.locator('.city-stage[data-elevator-loaded="true"]').waitFor({ timeout: 120000 })
  const floor = page.getByRole('button', { name: /^Select level 1:/ })
  await floor.focus()
  await floor.press('Enter')
  await page.locator('.city-stage[data-elevator-status="arrived"][data-room="about"]').waitFor({ timeout: 120000 })
  const trigger = page.locator('#observer-profile-trigger')
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: /Chong Kah Jun/ })
  await dialog.waitFor()
  assert.equal(await page.locator('.city-stage').getAttribute('data-profile-open'), 'true')
  assert.equal(await dialog.getByRole('button', { name: 'Close about profile' }).evaluate(element => document.activeElement === element), true)
  const columns = dialog.locator('.observer-column')
  assert.equal(await columns.count(), 3)
  const headerBefore = await dialog.locator('.observer-sheet-header').boundingBox()
  const portraitBefore = await columns.nth(1).evaluate(element => element.scrollTop)
  await columns.nth(0).evaluate(element => { element.scrollTop = element.scrollHeight })
  assert.equal(await columns.nth(1).evaluate(element => element.scrollTop), portraitBefore, 'Columns scroll independently')
  assert.deepEqual(await dialog.locator('.observer-sheet-header').boundingBox(), headerBefore)
  await dialog.getByRole('button', { name: 'Copy email' }).click()
  assert.match(await page.evaluate(() => navigator.clipboard.readText()), /@gmail\.com$/)
  const cvHref = await dialog.getByRole('link', { name: /Download CV/ }).getAttribute('href')
  assert.ok(cvHref?.includes('/cv/'), 'Profile offers the uploaded CV')
  assert.equal((await page.request.get(new URL(cvHref ?? '', page.url()).href)).status(), 200)
  const pdfUrl = new URL(`cv/${encodeURIComponent(cv.pdf.file)}`, page.url()).href
  const pdfOpened = page.waitForEvent('popup')
  await dialog.locator('.observer-sheet-header').getByRole('button', { name: 'Print CV' }).click()
  const pdfPage = await pdfOpened
  await pdfPage.waitForURL(pdfUrl)
  assert.equal(await pdfPage.evaluate(() => document.contentType), 'application/pdf')
  assert.equal(await pdfPage.evaluate(() => window.opener), null)
  assert.equal(await page.locator('.city-stage').getAttribute('data-profile-open'), 'true', 'Opening CV preserves the profile')
  await pdfPage.close()
  await columns.nth(0).evaluate(element => { element.scrollTop = 0 })
  await page.screenshot({ path: screenshotPath('profile-desktop.png') })

  await page.emulateMedia({ reducedMotion: 'no-preference' })
  const portrait = dialog.locator('.observer-portrait-images')
  const box = await portrait.boundingBox()
  assert.ok(box)
  await page.mouse.move(box.x + box.width * .35, box.y + box.height * .45)
  await page.mouse.move(box.x + box.width * .65, box.y + box.height * .55, { steps: 8 })
  await page.waitForFunction(() => document.querySelector('.observer-portrait-original')?.getAttribute('style')?.includes('visible') && document.querySelectorAll('.observer-portrait-original mask g rect').length > 10)
  assert.equal(await portrait.locator('mask > rect').getAttribute('opacity'), '0', 'Hover reveals a local trail, not the full photo')
  await page.screenshot({ path: screenshotPath('profile-portrait-trail.png') })
  await page.mouse.move(10, 10)
  await page.waitForFunction(() => document.querySelectorAll('.observer-portrait-original mask g rect').length === 0)
  await portrait.focus()
  await page.keyboard.press('Tab')
  await page.keyboard.press('Shift+Tab')
  assert.equal(await portrait.locator('mask > rect').getAttribute('opacity'), '1', 'Keyboard focus reveals the full photograph')
  await page.keyboard.press('Escape')
  await dialog.waitFor({ state: 'detached' })
  assert.equal(await trigger.evaluate(element => document.activeElement === element), true, 'Focus returns to profile opener')

  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 390, height: 844 })
  await trigger.click()
  await dialog.waitFor()
  const nav = dialog.getByRole('navigation', { name: 'Profile sections' })
  await nav.getByRole('button', { name: 'Record', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.observer-mobile-nav button[aria-current]')?.textContent === 'Record')
  const experience = dialog.getByRole('region', { name: 'Experience', exact: true })
  const second = experience.locator('article').nth(1)
  assert.equal(await second.locator('ul').isVisible(), false)
  await second.getByRole('button', { name: /Show .* highlights/ }).click()
  assert.equal(await second.locator('ul').isVisible(), true)
  await nav.getByRole('button', { name: 'Portrait', exact: true }).click()
  await portrait.hover()
  await page.mouse.move(5, 5)
  assert.equal(await portrait.locator('mask g rect').count(), 0, 'Reduced motion clears its local brush immediately on exit')
  await page.screenshot({ path: screenshotPath('profile-mobile.png') })
  for (const viewport of [{ width: 768, height: 900 }, { width: 320, height: 640 }]) {
    await page.setViewportSize(viewport)
    const bounds = await dialog.boundingBox()
    assert.ok(bounds && bounds.width <= viewport.width && bounds.height <= viewport.height)
    assert.equal(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth), true)
    assert.equal(await dialog.getByRole('button', { name: /Return to office/ }).isVisible(), true)
    assert.equal(await dialog.locator('.observer-sheet-header').getByRole('button', { name: 'Print CV' }).isVisible(), true)
  }
  await dialog.getByRole('button', { name: /Return to office/ }).click()
  await page.locator('.city-stage[data-room="about"][data-profile-open="false"]').waitFor()
  assert.deepEqual(errors, [])
  await context.close()
  console.log('PASS profile: desktop independent columns, copy, portrait trail/fade/keyboard/reduced motion, mobile navigation/details, responsive bounds and office/focus return')
} finally {
  await browser?.close()
  await new Promise<void>(done => server.httpServer.close(() => done()))
}
