import assert from 'node:assert/strict'
import { preview, createServer } from 'vite'
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
const videoProjects=JSON.parse(fs.readFileSync(new URL('../public/models/rooms/projects/scene.json',import.meta.url))).projects
const approachY=id=>{const project=videoProjects.find(project=>project.id===id);return project.position[1]-Math.abs(project.position[0])}
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/tmp/opencode/browser-check/node_modules/playwright/index.mjs')
const server=process.env.VIDEO_TEST_DEV?await createServer({server:{host:'127.0.0.1',port:5196,strictPort:true}}):await preview({preview:{host:'127.0.0.1',port:5196,strictPort:true}})
if(process.env.VIDEO_TEST_DEV) await server.listen()
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']})
const errors=[]
async function enter(viewport,motion='no-preference',sound=false) {
  const page=await browser.newPage({viewport,reducedMotion:motion})
  page.on('pageerror',error=>errors.push(error.message))
  await page.addInitScript(()=>{const raf=requestAnimationFrame.bind(window);window.__rafCount=0;window.requestAnimationFrame=callback=>{window.__rafCount++;return raf(callback)}})
  const requests=[];page.on('request',request=>{if(request.url().includes('/videos/'))requests.push(request.url())})
  await page.goto('http://127.0.0.1:5196/damien-portfolio/')
  await page.getByRole('button',{name:sound?/Enable sound/:'Continue muted'}).click()
  await page.locator('.city-stage[data-loaded="true"]').waitFor({timeout:120000})
  await page.getByRole('button',{name:/Choose a floor/}).click()
  await page.locator('.city-stage[data-elevator-loaded="true"]').waitFor({timeout:120000})
  const floor=page.getByRole('button',{name:/Select level 3:/});await floor.focus();await floor.press('Enter')
  await page.locator('.city-stage[data-elevator-status="arrived"][data-room="projects"]').waitFor({timeout:120000})
  return {page,requests,dock:page.locator('[data-project-video="agent-property"]')}
}
async function outside(dock) {
  const bounds=await dock.boundingBox(),board=await dock.evaluate(node=>({left:Number(node.dataset.boardLeft),right:Number(node.dataset.boardRight),top:Number(node.dataset.boardTop),bottom:Number(node.dataset.boardBottom)}))
  assert.ok(bounds.x+bounds.width<board.left||bounds.x>board.right||bounds.y+bounds.height<board.top||bounds.y>board.bottom,'Prompt/controls overlap the video board')
}
async function visiblePixels(page,dock) {
  await dock.evaluate(node=>{window.__testedVideoDock=node})
  await page.waitForFunction(()=>window.__testedVideoDock.dataset.renderedSurface==='video')
  const region=await dock.evaluate(node=>({left:Number(node.dataset.boardLeft),right:Number(node.dataset.boardRight),top:Number(node.dataset.boardTop),bottom:Number(node.dataset.boardBottom)}))
  const png=await page.screenshot()
  const score=Number(execFileSync('python3',['-c',`import sys,json,io\nfrom PIL import Image\nr=json.loads(sys.argv[1]);im=Image.open(io.BytesIO(sys.stdin.buffer.read())).convert('RGB');w,h=im.size\nx0=max(0,int(r['left']+20));x1=min(w,int(r['right']-20));y0=max(0,int(r['top']+20));y1=min(h,int(r['bottom']-20))\np=list(im.crop((x0,y0,x1,y1)).resize((64,36)).getdata());print(sum(sum(c)/3>80 for c in p)/len(p))`,JSON.stringify(region)],{input:png}).toString())
  assert.ok(score>.15,`Playback is progressing but the rendered board is blank (${score})`)
}
try {
  const {page,requests,dock}=await enter({width:1440,height:900})
  await page.waitForFunction(()=>document.querySelector('canvas').dataset.roomFov)
  await page.evaluate(()=>{
    window.__maximumPlayingVideos=0
    const check=()=>{window.__maximumPlayingVideos=Math.max(window.__maximumPlayingVideos,[...document.querySelectorAll('[data-project-video]')].filter(node=>node.dataset.videoPaused==='false').length)}
    const observer=new MutationObserver(check)
    observer.observe(document.querySelector('.city-stage'),{subtree:true,attributes:true,attributeFilter:['data-video-paused']})
  })
  assert.ok(!requests.some(url=>url.includes('myrumawip-full')))
  const walkingFov=await page.locator('canvas').getAttribute('data-room-fov')
  await page.locator('#room-progress').evaluate((input,y)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,String(y));input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))},approachY('agent-property'))
  await page.waitForFunction(y=>Math.abs(Number(document.querySelector('.city-stage').dataset.roomY)-y)<.02,approachY('agent-property'))
  await page.locator('.room-more-controls summary').click()
  await page.locator('.room-more-controls').getByRole('button',{name:'Look left',exact:true}).click()
  await page.getByRole('button',{name:'Hide menu'}).click()
  await dock.locator('.project-video-description').waitFor({state:'visible',timeout:20000})
  await page.waitForFunction(()=>document.querySelector('[data-project-video]').dataset.videoPaused==='false')
  await outside(dock)
  assert.equal(await page.locator('canvas').getAttribute('data-room-fov'),walkingFov,'Looking at a nearby video must not change the walking FOV')
  await visiblePixels(page,dock)
  assert.ok(!requests.some(url=>url.includes('myrumawip-full')))
  // Hand off between two previews on the same visit; never overlap decoders.
  await page.getByRole('button',{name:'Show menu'}).click()
  await page.locator('#room-progress').evaluate((input,y)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,String(y));input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))},approachY('report-automation'))
  await page.waitForFunction(y=>Math.abs(Number(document.querySelector('.city-stage').dataset.roomY)-y)<.02,approachY('report-automation'))
  if(!await page.locator('.room-more-controls').evaluate(element=>element.open))await page.locator('.room-more-controls summary').click()
  for(let i=0;i<2;i++)await page.locator('.room-more-controls').getByRole('button',{name:'Look right',exact:true}).click()
  await page.waitForFunction(()=>document.querySelector('[data-project-video="report-automation"]').dataset.videoPaused==='false'&&document.querySelector('[data-project-video="agent-property"]').dataset.videoPaused==='true')
  assert.equal(await page.locator('canvas').getAttribute('data-room-fov'),walkingFov,'Walking past videos must keep the lens fixed')
  await page.locator('#room-progress').evaluate((input,y)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,String(y));input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))},approachY('agent-property'))
  await page.waitForFunction(y=>Math.abs(Number(document.querySelector('.city-stage').dataset.roomY)-y)<.02,approachY('agent-property'))
  for(let i=0;i<2;i++)await page.locator('.room-more-controls').getByRole('button',{name:'Look left',exact:true}).click()
  await page.getByRole('button',{name:'Hide menu'}).click()
  await page.waitForFunction(()=>document.querySelector('[data-project-video="agent-property"]').dataset.videoPaused==='false'&&document.querySelector('[data-project-video="report-automation"]').dataset.videoPaused==='true')
  const center=await dock.evaluate(node=>({x:(Number(node.dataset.boardLeft)+Number(node.dataset.boardRight))/2,y:(Number(node.dataset.boardTop)+Number(node.dataset.boardBottom))/2}))
  await page.mouse.click(center.x,center.y)
  await page.locator('.city-stage[data-room-view="project"][data-card-focus-framed="true"]').waitFor({timeout:30000})
  await page.waitForFunction(()=>Number(document.querySelector('[data-project-video]').dataset.videoDuration)>40)
  await dock.getByRole('button',{name:'Pause video',exact:true}).waitFor({state:'visible'})
  await outside(dock)
  await visiblePixels(page,dock)
  assert.ok(requests.some(url=>url.includes('myrumawip-full')))
  await dock.getByRole('button',{name:'Pause video',exact:true}).click()
  await page.waitForFunction(()=>document.querySelector('[data-project-video]').dataset.videoPaused==='true')
  assert.ok(await page.evaluate(()=>window.__maximumPlayingVideos)<=1,'Never decode/play multiple project videos at the same time')
  await page.locator('.city-stage[data-card-focus-settled="true"]').waitFor({timeout:30000})
  await page.evaluate(()=>document.dispatchEvent(new PointerEvent('pointerleave',{pointerType:'mouse'})))
  await page.waitForTimeout(500)
  const frames=await page.evaluate(()=>window.__rafCount);await page.waitForTimeout(700)
  assert.ok(await page.evaluate(()=>window.__rafCount)-frames<=2,'Paused video must settle the Canvas')
  await dock.getByRole('button',{name:'Play video',exact:true}).click()
  await page.getByRole('button',{name:'Open navigation guide'}).click()
  await page.locator('.portfolio-guide[open]').waitFor()
  await page.waitForFunction(()=>document.querySelector('[data-project-video]').dataset.videoPaused==='true')
  await page.keyboard.press('Escape');await page.locator('.portfolio-guide[open]').waitFor({state:'detached'})
  await page.waitForFunction(()=>document.querySelector('[data-project-video]').dataset.videoPaused==='false')
  await page.getByRole('button',{name:/Back to hallway/}).click()
  await page.locator('.city-stage[data-room-view="main"]').waitFor()
  await page.getByRole('button',{name:'Show menu'}).click()
  await page.locator('#room-progress').evaluate(input=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'30');input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))})
  await page.waitForFunction(()=>document.querySelector('[data-project-video]').dataset.videoPaused==='true')
  await page.close()
  console.log('PASS exclusive camera-facing preview handoffs, fixed walking FOV, full native picks and pause/idle/modal/off-screen cleanup')
  for(const [viewport,sound] of [[{width:390,height:844},false],[{width:1440,height:900},true]]) {
    const visit=await enter(viewport,'reduce',sound)
    await visit.page.locator('.room-index-button').filter({hasText:'Agent Property'}).click()
    await visit.page.locator('.city-stage[data-card-focus-framed="true"]').waitFor({timeout:30000})
    await visit.dock.getByRole('button',{name:'Pause video',exact:true}).waitFor({state:'visible',timeout:20000})
    await outside(visit.dock)
    if(sound) {
      await visit.page.waitForFunction(()=>!document.getElementById('background-music-audio').paused)
      await visit.dock.getByRole('button',{name:'Sound off',exact:true}).click()
      await visit.dock.getByRole('button',{name:'Sound on',exact:true}).waitFor()
      await visit.page.waitForFunction(()=>document.getElementById('background-music-audio').paused)
      await visit.dock.getByRole('button',{name:'Sound on',exact:true}).click()
      await visit.page.waitForFunction(()=>!document.getElementById('background-music-audio').paused)
    }
    await visit.page.getByRole('button',{name:/Back to hallway/}).click();await visit.page.close()
  }
  assert.deepEqual(errors,[])
  for(const [id,y,direction,name,duration] of [['report-automation',approachY('report-automation'),'Look right','MyReport',40],['Aria',approachY('Aria'),'Look left','DWMLight',55]]) {
    const visit=await enter({width:1440,height:900})
    const target=visit.page.locator(`[data-project-video="${id}"]`)
    assert.ok(!visit.requests.some(url=>url.includes(`${id==='Aria'?'dwmlight':'myreport'}-full`)))
    await visit.page.locator('#room-progress').evaluate((input,y)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,String(y));input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))},y)
    await visit.page.waitForFunction(y=>Math.abs(Number(document.querySelector('.city-stage').dataset.roomY)-y)<.02,y)
    await visit.page.locator('.room-more-controls summary').click()
    await visit.page.locator('.room-more-controls').getByRole('button',{name:direction,exact:true}).click()
    await visit.page.getByRole('button',{name:'Hide menu'}).click()
    await target.locator('.project-video-description').waitFor({state:'visible',timeout:20000})
    await target.evaluate(node=>{window.__testedVideoDock=node})
    await visit.page.waitForFunction(()=>window.__testedVideoDock.dataset.videoPaused==='false')
    assert.ok((await visit.page.locator('[data-project-video]').evaluateAll(nodes=>nodes.filter(node=>node.dataset.videoPaused==='false').length))<=1,'Only the camera-facing preview should be playing')
    await outside(target);await visiblePixels(visit.page,target)
    await target.getByRole('button',{name:new RegExp(`Watch ${name}`)}).click()
    await visit.page.locator('.city-stage[data-room-view="project"][data-card-focus-framed="true"]').waitFor({timeout:30000})
    await visit.page.waitForFunction(duration=>Number(window.__testedVideoDock.dataset.videoDuration)>duration,duration)
    await target.getByRole('button',{name:'Pause video',exact:true}).waitFor({state:'visible'})
    await outside(target);await visiblePixels(visit.page,target)
    const others=await visit.page.locator(`[data-project-video]:not([data-project-video="${id}"])`).evaluateAll(nodes=>nodes.map(node=>node.dataset.videoPaused))
    assert.ok(others.every(paused=>paused!=='false'),'Other previews must pause while a walkthrough is focused')
    await visit.page.getByRole('button',{name:/Back to hallway/}).click();await visit.page.close()
    console.log(`PASS ${name}: correct preview/full files, visible pixels, outside prompt and other-player suspension`)
  }
  assert.deepEqual(errors,[])
  console.log('PASS mobile/reduced-motion full playback and non-persistent video/background-music audio focus')
} finally {await browser.close();if(process.env.VIDEO_TEST_DEV)await server.close();else await new Promise(resolve=>server.httpServer.close(resolve))}
