import assert from 'node:assert/strict'
import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'
import { preview } from 'vite'
import { chromium, chromeExecutable, installBrowserHelpers, screenshotPath } from './browser_tools.mts'
import type { Page } from 'playwright'
interface PlayRecord { active: boolean; src: string; failure?: string }
declare global { interface Window {
  audioChecks: { plays: PlayRecord[]; contexts: { active: boolean }[]; resumes: { active: boolean }[] }
  testHidden: boolean
} }

const root = resolve(fileURLToPath(new URL('..', import.meta.url)))
async function seekCity(page: Page, frame: number) {
  await page.locator('#city-timeline').evaluate((input, value) => {
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')!.set!.call(input, String(value))
    input.dispatchEvent(new Event('input', { bubbles: true }));input.dispatchEvent(new Event('change', { bubbles: true }))
  }, frame)
}
const server = await preview({ root, build: { outDir: process.env.VITE_TEST_OUT_DIR || 'dist' }, preview: { host: '127.0.0.1', port: 5196, strictPort: true } })
let browser
try {
  browser = await chromium.launch({ executablePath: chromeExecutable, headless: true,
    args: ['--no-sandbox', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--autoplay-policy=document-user-activation-required'] })
  const errors: string[] = []
  const context = await browser.newContext({ viewport: { width: 1280, height: 800 }, reducedMotion: 'reduce' })
  await installBrowserHelpers(context,() => {
    navigator.getAutoplayPolicy = () => 'disallowed'
    window.audioChecks = { plays: [], contexts: [], resumes: [] }
    const play = HTMLMediaElement.prototype.play
    HTMLMediaElement.prototype.play = function () {
      const record: PlayRecord = { active: navigator.userActivation.isActive, src: this.src }
      window.audioChecks.plays.push(record)
      return play.call(this).catch(error => { record.failure = error.name;throw error })
    }
    const NativeContext = window.AudioContext
    window.AudioContext = new Proxy(NativeContext, {
      construct(target, args) {
        window.audioChecks.contexts.push({ active: navigator.userActivation.isActive })
        const audio = Reflect.construct(target, args) as AudioContext
        const resume = audio.resume.bind(audio)
        audio.resume = () => { window.audioChecks.resumes.push({ active: navigator.userActivation.isActive });return resume() }
        return audio
      },
    })
  })
  const page = await context.newPage()
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => {
    if (/autoplay|AudioContext.*(prevented|allowed)|could not start/i.test(message.text())) errors.push(message.text())
  })
  const audioRequests: string[] = []
  page.on('request', request => { if (/\/audio\/.*\.mp3/.test(request.url())) audioRequests.push(request.url()) })
  const visit = async (prompt = true) => {
    await page.goto('http://127.0.0.1:5196/damien-portfolio/')
    await page.locator('.background-music').waitFor()
    if (prompt) await page.getByRole('dialog', { name: 'Enter with sound?' }).waitFor()
    else assert.equal(await page.locator('.audio-consent').count(), 0, 'A remembered choice must skip the prompt')
    await page.waitForTimeout(250)
    const enabled = await page.evaluate(() => (JSON.parse(localStorage.getItem('damien-portfolio:background-music')!) as { enabled: boolean }).enabled)
    if (!prompt && enabled) {
      await page.waitForFunction(() => window.audioChecks.plays[0]?.failure === 'NotAllowedError')
      assert.equal(await page.evaluate(() => window.audioChecks.plays.length), 1, 'Remembered enabled music gets one refresh attempt')
      assert.equal(await page.locator('.background-music').getAttribute('data-autoplay-blocked'), 'true')
    } else assert.deepEqual(await page.evaluate(() => window.audioChecks.plays), [], 'No music autoplay without remembered approval')
    assert.deepEqual(await page.evaluate(() => window.audioChecks.contexts), [], 'No Web Audio context before consent')
    assert.equal(await page.locator('.background-music-toggle').first().getAttribute('aria-pressed'), 'false', 'Paused music must not be announced as on')
    assert.equal(await page.locator('.background-music').getAttribute('data-music-state'), await page.evaluate(() => (JSON.parse(localStorage.getItem('damien-portfolio:background-music')!) as { enabled: boolean }).enabled) ? 'ready' : 'off')
  }
  await visit()
  assert.equal(audioRequests.length, 0, 'Declined/unresolved sound should not fetch audio')
  assert.equal(await page.locator('.audio-consent-bars span').count(), 5)
  assert.equal(await page.locator('.audio-consent-bars span').first().evaluate(bar => getComputedStyle(bar).animationName), 'none', 'Reduced motion stops the sound bars')
  await page.screenshot({ path: screenshotPath('sound-prompt-desktop.png') })
  assert.equal(await page.getByRole('button', { name: 'Enable sound', exact: true }).evaluate(button => button === document.activeElement), true)
  await page.keyboard.press('Tab')
  assert.equal(await page.getByRole('button', { name: 'Continue muted', exact: true }).evaluate(button => button === document.activeElement), true)
  await page.keyboard.press('Tab')
  assert.equal(await page.getByRole('button', { name: 'Enable sound', exact: true }).evaluate(button => button === document.activeElement), true)
  await page.getByRole('button', { name: 'Enable sound', exact: true }).evaluate((button: HTMLButtonElement) => button.click())
  assert.equal(await page.getByRole('dialog', { name: 'Enter with sound?' }).count(), 1, 'Synthetic clicks must not grant sound permission')
  assert.equal(await page.evaluate(() => window.audioChecks.contexts.length), 0)
  await page.locator('.background-music button').evaluateAll((buttons: HTMLButtonElement[]) => buttons.forEach(button => button.click()))
  assert.equal(await page.evaluate(() => window.audioChecks.plays.length), 0, 'Inert background controls cannot bypass startup consent')
  assert.equal(await page.evaluate(() => window.audioChecks.contexts.length), 0)
  await page.getByRole('button', { name: 'Continue muted', exact: true }).click()
  await page.getByRole('dialog', { name: 'Enter with sound?' }).waitFor({ state: 'detached' })
  await page.waitForTimeout(200)
  assert.equal(await page.evaluate(() => document.querySelector<HTMLAudioElement>('#background-music-audio')!.paused), true)
  assert.equal(await page.evaluate(() => window.audioChecks.contexts.length), 0)
  for (const key of ['background-music', 'sound-effects']) {
    assert.equal(await page.evaluate(name => (JSON.parse(localStorage.getItem(`damien-portfolio:${name}`)!) as { enabled: boolean }).enabled, key), false)
  }
  await visit(false)
  assert.equal(await page.evaluate(() => document.querySelector<HTMLAudioElement>('#background-music-audio')!.paused), true)
  assert.equal(await page.getByRole('button', { name: 'Enable interaction sound effects', exact: true }).count(), 1)
  await page.getByRole('button', { name: 'Play background music', exact: true }).click()
  await page.waitForFunction(() => !document.querySelector<HTMLAudioElement>('#background-music-audio')!.paused)
  await page.waitForSelector('.background-music[data-music-state=playing]')
  assert.equal(await page.locator('.background-music-toggle').first().getAttribute('aria-pressed'), 'true')
  assert.equal(await page.evaluate(() => window.audioChecks.contexts.length), 0, 'Music may be enabled independently of effects')
  await page.getByRole('button', { name: 'Pause background music', exact: true }).click()
  await page.getByRole('button', { name: 'Enable interaction sound effects', exact: true }).click()
  await page.waitForFunction(() => window.audioChecks.contexts.length === 1)
  assert.equal(await page.evaluate(() => window.audioChecks.contexts[0].active), true)
  await page.getByRole('button', { name: 'Mute interaction sound effects', exact: true }).click()

  await page.evaluate(() => {
    localStorage.setItem('damien-portfolio:background-music', JSON.stringify({ enabled: true, volume: .27 }))
    localStorage.setItem('damien-portfolio:sound-effects', JSON.stringify({ enabled: true, volume: .33 }))
  })
  await visit(false)
  await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')))
  assert.equal(await page.evaluate(() => window.audioChecks.plays.length), 1, 'Visibility must not repeat a rejected refresh attempt')
  await page.getByRole('button', { name: 'Open navigation guide', exact: true }).click()
  await page.waitForFunction(() => !document.querySelector<HTMLAudioElement>('#background-music-audio')!.paused)
  assert.equal(await page.evaluate(() => window.audioChecks.contexts.length), 1)
  assert.equal(await page.evaluate(() => window.audioChecks.contexts[0].active), true)
  assert.equal(await page.evaluate(() => window.audioChecks.plays[1].active), true)
  assert.equal(await page.evaluate(() => document.querySelector<HTMLAudioElement>('#background-music-audio')!.volume), .35, 'Music uses the fixed mix, not a legacy saved level')
  assert.equal(await page.evaluate(() => (JSON.parse(localStorage.getItem('damien-portfolio:sound-effects')!) as { volume: number }).volume), .45, 'Effects use the fixed mix')
  assert.equal(await page.locator('.background-music input').count(), 0, 'Toggle-only controls must not expose volume adjustment')
  await page.keyboard.press('Escape')
  await page.locator('.portfolio-guide[open]').waitFor({ state:'detached' })
  assert.equal(await page.getByRole('button', { name: 'Mute interaction sound effects', exact: true }).count(), 1)
  await page.evaluate(() => {
    window.testHidden = true
    Object.defineProperty(document, 'hidden', { configurable: true, get: () => window.testHidden })
    document.dispatchEvent(new Event('visibilitychange'))
  })
  await page.waitForFunction(() => document.querySelector<HTMLAudioElement>('#background-music-audio')!.paused)
  await page.waitForSelector('.background-music[data-music-state=ready]')
  assert.equal(await page.locator('.background-music-toggle').first().getAttribute('aria-pressed'), 'false')
  await page.evaluate(() => { window.testHidden = false;document.dispatchEvent(new Event('visibilitychange')) })
  await page.waitForFunction(() => !document.querySelector<HTMLAudioElement>('#background-music-audio')!.paused)

  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => localStorage.removeItem('damien-portfolio:audio-consent'))
  await visit()
  const bounds = await page.getByRole('dialog', { name: 'Enter with sound?' }).boundingBox()
  assert.ok(bounds)
  assert(bounds.x >= 0 && bounds.x + bounds.width <= 390)
  await page.screenshot({ path: screenshotPath('sound-prompt-mobile.png') })
  await page.keyboard.press('Escape')
  await page.getByRole('dialog', { name: 'Enter with sound?' }).waitFor({ state: 'detached' })
  assert.equal(await page.evaluate(() => window.audioChecks.plays.length), 0)
  assert.equal(await page.evaluate(() => window.audioChecks.contexts.length), 0)
  await visit(false)
  assert.equal(await page.evaluate(() => document.querySelector<HTMLAudioElement>('#background-music-audio')!.paused), true)
  assert.equal(await page.locator('.sound-effects-toggle').getAttribute('aria-label'), 'Enable interaction sound effects')
  assert.equal(await page.locator('.sound-effects-toggle').isVisible(), false, 'Mobile SFX control lives in the settings sheet')
  await page.evaluate(() => localStorage.removeItem('damien-portfolio:audio-consent'))
  await visit()
  await page.keyboard.press('Enter')
  await page.getByRole('dialog', { name: 'Enter with sound?' }).waitFor({ state: 'detached' })
  await page.waitForFunction(() => !document.querySelector<HTMLAudioElement>('#background-music-audio')!.paused)
  assert.equal(await page.evaluate(() => window.audioChecks.plays[0].active), true)
  assert.equal(await page.getByRole('button', { name: 'Show sound prompt again', exact: true }).count(), 0, 'No center prompt-reopen button')
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.evaluate(() => localStorage.removeItem('damien-portfolio:audio-consent'))
  await visit()
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  assert.equal(await page.locator('.audio-consent-bars span').first().evaluate(bar => getComputedStyle(bar).animationName), 'audio-consent-wave')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.keyboard.press('m')
  await page.getByRole('dialog', { name: 'Enter with sound?' }).waitFor({ state: 'detached' })
  assert.equal(await page.evaluate(() => document.querySelector<HTMLAudioElement>('#background-music-audio')!.paused), true)
  assert.equal(await page.evaluate(() => localStorage.getItem('damien-portfolio:audio-consent')), 'muted')
  await visit(false)

  const preferencesButton = page.getByRole('button', { name: 'Open sound preferences', exact: true })
  const helpButton = page.getByRole('button', { name: 'Open navigation guide', exact: true })
  await preferencesButton.hover()
  await page.getByRole('tooltip', { name: 'Sound preferences', exact: true }).waitFor()
  assert.equal(await page.evaluate(() => window.audioChecks.plays.length), 0, 'Hover is silent')
  await helpButton.hover()
  await page.getByRole('tooltip', { name: 'Navigation guide', exact: true }).waitFor()
  await preferencesButton.focus()
  await page.getByRole('tooltip', { name: 'Sound preferences', exact: true }).waitFor()
  await page.keyboard.press('Escape')
  await page.getByRole('tooltip', { name: 'Sound preferences', exact: true }).waitFor({ state: 'hidden' })
  await preferencesButton.click()
  await page.getByRole('dialog', { name: 'Enter with sound?', exact: true }).waitFor()
  const pausedFrame = await page.locator('.city-stage').getAttribute('data-frame')
  await page.keyboard.press('PageDown')
  assert.equal(await page.locator('.city-stage').getAttribute('data-frame'), pausedFrame, 'Preferences block journey input')
  assert.equal(await page.locator('.audio-consent [role=switch]').count(), 0, 'Preferences reuse the YES/MUTED interface')
  assert.equal(await page.locator('.audio-consent-bars span').count(), 5)
  await page.getByRole('button', { name: 'Enable sound', exact: true }).click()
  await page.getByRole('dialog', { name: 'Enter with sound?', exact: true }).waitFor({ state: 'detached' })
  await page.waitForSelector('.background-music[data-music-state=playing]')
  assert.equal(await page.evaluate(() => (JSON.parse(localStorage.getItem('damien-portfolio:sound-effects')!) as { enabled: boolean }).enabled), true)
  await preferencesButton.click()
  await page.getByRole('dialog', { name: 'Enter with sound?', exact: true }).waitFor()
  await page.keyboard.press('Escape')
  await page.getByRole('dialog', { name: 'Enter with sound?', exact: true }).waitFor({ state: 'detached' })
  assert.equal(await page.evaluate(() => (JSON.parse(localStorage.getItem('damien-portfolio:background-music')!) as { enabled: boolean }).enabled), true, 'Cancelling preferences preserves the choice')
  await preferencesButton.click()
  await page.getByRole('dialog', { name: 'Enter with sound?', exact: true }).waitFor()
  await page.keyboard.press('m')
  await page.getByRole('dialog', { name: 'Enter with sound?', exact: true }).waitFor({ state: 'detached' })
  await page.waitForSelector('.background-music[data-music-state=off]')
  assert.equal(await page.evaluate(() => (JSON.parse(localStorage.getItem('damien-portfolio:sound-effects')!) as { enabled: boolean }).enabled), false)
  assert.equal(await preferencesButton.evaluate(button => button === document.activeElement), true, 'Preferences restore trigger focus')
  await visit(false)

  await page.evaluate(() => {
    localStorage.setItem('damien-portfolio:background-music', JSON.stringify({ enabled: true, volume: .18 }))
    localStorage.setItem('damien-portfolio:sound-effects', JSON.stringify({ enabled: false, volume: .45 }))
  })
  await visit(false)
  const musicButton = page.getByRole('button', { name: 'Play background music', exact: true })
  assert.match((await musicButton.textContent())!, /Music ready/)
  await musicButton.click()
  await page.waitForSelector('.background-music[data-music-state=playing]')
  assert.equal(await page.evaluate(() => document.querySelector<HTMLAudioElement>('#background-music-audio')!.paused), false)
  assert.equal(await page.evaluate(() => (JSON.parse(localStorage.getItem('damien-portfolio:background-music')!) as { enabled: boolean }).enabled), true, 'Clicking ready music must play, not disable the saved preference')
  assert.equal(await page.evaluate(() => window.audioChecks.contexts.length), 0, 'Music starts without enabling muted SFX')
  // Selecting YES again must not pause a track already started by the icon's
  // user gesture, even when it changes the stored consent from muted to enabled.
  await preferencesButton.click()
  await page.getByRole('dialog', { name: 'Enter with sound?', exact: true }).waitFor()
  await page.getByRole('button', { name: 'Enable sound', exact: true }).click()
  await page.getByRole('dialog', { name: 'Enter with sound?', exact: true }).waitFor({ state: 'detached' })
  await page.waitForSelector('.background-music[data-music-state=playing]')
  assert.equal(await page.evaluate(() => document.querySelector<HTMLAudioElement>('#background-music-audio')!.paused), false, 'Updating YES must not clean up existing playback')
  await page.getByRole('button', { name: 'Mute interaction sound effects', exact: true }).click()
  await page.getByRole('button', { name: 'Pause background music', exact: true }).click()
  await page.waitForSelector('.background-music[data-music-state=off]')
  assert.equal(await page.evaluate(() => document.querySelector<HTMLAudioElement>('#background-music-audio')!.paused), true)
  assert.equal(await page.locator('.background-music-toggle').first().getAttribute('aria-pressed'), 'false')

  const checkLayout = async (progress: boolean) => {
    for (const width of [1280, 768, 390]) {
      await page.setViewportSize({ width, height: 844 })
       const audio = await page.locator('.background-music').boundingBox()
       assert.ok(audio)
      assert(audio.x >= 0 && audio.x + audio.width <= width)
       const header = await page.locator('.city-topline-actions').boundingBox()
       assert.ok(header)
      assert(header.x >= 0 && header.x + header.width <= width, 'Header icons must fit narrow viewports')
       assert.equal(await page.locator('.audio-choice-reopen').count(), 0)
      if (progress) {
         const bar = await page.locator('.city-controls:not([hidden])').boundingBox()
         assert.ok(bar)
        assert(audio.y + audio.height <= bar.y - (width <= 600 ? 4 : 8), 'Audio panel must sit above the progress track with the reference mobile dock gap')
      } else {
        assert.equal(await page.locator('.city-controls:not([hidden])').count(), 0)
        assert.equal(await page.locator('.background-music').evaluate(node => getComputedStyle(node).bottom), width <= 600 ? '16px' : '20px', 'Return audio controls to the corner without progress')
      }
    }
  }
  await checkLayout(true)
  const enterRoom = async (number: number) => {
    await page.getByRole('button', { name: /^Choose a floor/ }).click()
    await page.waitForSelector('.city-stage[data-interactive=true][data-elevator-loaded=true]', { timeout: 90000 })
    await page.getByRole('button', { name: new RegExp(`^Select level ${number}:`) }).focus()
    await page.keyboard.press('Enter')
    await page.waitForSelector('.city-stage[data-elevator-status=arrived][data-room-loaded=true]', { timeout: 90000 })
  }
  await enterRoom(1)
  await checkLayout(false)
  await page.locator('#city').focus()
  await page.keyboard.press('Home')
  await page.keyboard.press('PageUp')
  await page.getByRole('button', { name: 'Yes, return to elevator', exact: true }).click()
  await page.waitForSelector('.city-stage[data-elevator-status=idle]', { timeout: 90000 })
  await enterRoom(4)
  await checkLayout(true)
  await page.setViewportSize({ width: 312, height: 678 })
  await page.goto('http://127.0.0.1:5196/damien-portfolio/')
  await page.waitForSelector('.city-stage[data-loaded=true]')
  const cluster = await page.locator('.city-topline-actions').boundingBox()
  assert.ok(cluster)
  assert.equal(cluster.x + cluster.width, 296, 'Reference HUD has a 16px right inset')
  assert.equal(cluster.y, 16)
  for (const button of [preferencesButton, helpButton, page.getByRole('button', { name: 'Choose a floor', exact: true })]) {
    const bounds = await button.boundingBox()
    assert.ok(bounds)
    assert.equal(bounds.width, 44)
    assert.equal(bounds.height, 44, 'Reference buttons retain touch-sized targets')
  }
  assert.equal(await page.locator('.city-topline > span').count(), 0, 'No top-left branding')
  assert.equal(await page.locator('.mobile-journey-stop').count(), 0, 'Mobile uses the continuous desktop slider without checkpoint buttons')
  assert.equal(await page.locator('#city-timeline').isVisible(), true)
  await seekCity(page, 145)
  await page.waitForSelector('.city-stage[data-frame="145"][data-rendered-frame="145"]')
  await seekCity(page, 383)
  await page.waitForSelector('.city-stage[data-frame="383"][data-rendered-frame="383"]', { timeout: 90000 })
  await seekCity(page, 145)
  await page.waitForSelector('.city-stage[data-frame="145"][data-rendered-frame="145"]')
  await page.mouse.move(0, 0)
  await page.screenshot({ path: screenshotPath('mobile-hud.png') })
  await preferencesButton.click()
  await page.getByRole('dialog', { name: 'Settings', exact: true }).waitFor()
  const settingsFrame = await page.locator('.city-stage').getAttribute('data-frame')
  await page.keyboard.press('PageDown')
  await page.mouse.wheel(0, 600)
  assert.equal(await page.locator('.city-stage').getAttribute('data-frame'), settingsFrame, 'Mobile settings own navigation input')
  const musicPreference = page.getByRole('button', { name: 'Toggle background music', exact: true })
  const effectsPreference = page.getByRole('button', { name: 'Toggle interaction sound effects', exact: true })
  const musicBefore = await musicPreference.getAttribute('aria-pressed')
  const effectsBefore = await effectsPreference.getAttribute('aria-pressed')
  await musicPreference.click()
  assert.equal(await musicPreference.getAttribute('aria-pressed'), String(musicBefore !== 'true'))
  assert.equal(await effectsPreference.getAttribute('aria-pressed'), effectsBefore, 'Music toggle preserves SFX choice')
  await effectsPreference.click()
  assert.equal(await effectsPreference.getAttribute('aria-pressed'), String(effectsBefore !== 'true'))
  assert.equal(await musicPreference.getAttribute('aria-pressed'), String(musicBefore !== 'true'), 'SFX toggle preserves music choice')
  assert.equal(await page.getByRole('dialog').getByRole('link', { name: /^Music credit:/ }).count(), 1)
  await page.getByRole('dialog').getByRole('link', { name: /^Music credit:/ }).focus()
  await page.keyboard.press('Tab')
  assert.equal(await page.getByRole('button', { name: 'Close sound preferences' }).evaluate(button => button === document.activeElement), true, 'Mobile settings trap keyboard focus')
  await page.mouse.move(0, 0)
  await page.screenshot({ path: screenshotPath('mobile-hud-settings.png') })
  await page.keyboard.press('Escape')
  await page.getByRole('dialog').waitFor({ state: 'detached' })
  assert.equal(await preferencesButton.evaluate(button => button === document.activeElement), true)
  const mobileContext = await browser.newContext({ viewport: { width: 312, height: 678 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' })
  await installBrowserHelpers(mobileContext, () => {
    localStorage.setItem('damien-portfolio:audio-consent', 'muted')
    localStorage.setItem('damien-portfolio:background-music', JSON.stringify({ enabled: false }))
    localStorage.setItem('damien-portfolio:sound-effects', JSON.stringify({ enabled: false }))
  })
  const mobilePage = await mobileContext.newPage()
  mobilePage.on('pageerror', error => errors.push(error.message))
  await mobilePage.goto('http://127.0.0.1:5196/damien-portfolio/')
  await mobilePage.waitForSelector('.city-stage[data-loaded=true]')
  const touchSession = await mobileContext.newCDPSession(mobilePage)
  await touchSession.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 150, y: 480 }] })
  await touchSession.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 150, y: 380 }] })
  await touchSession.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await mobilePage.waitForFunction(() => Number(document.querySelector<HTMLElement>('.city-stage')?.dataset.frame) > 50)
  await mobilePage.locator('#city-timeline').focus();await mobilePage.keyboard.press('Home')
  await mobilePage.waitForSelector('.city-stage[data-frame="1"]')
  const slider = await mobilePage.locator('#city-timeline').boundingBox()
  assert.ok(slider)
  await touchSession.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: slider.x + 3, y: slider.y + slider.height / 2 }] })
  await touchSession.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: slider.x + slider.width / 2, y: slider.y + slider.height / 2 }] })
  await touchSession.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await mobilePage.waitForFunction(() => {
    const frame = Number(document.querySelector<HTMLElement>('.city-stage')?.dataset.frame)
    return frame > 650 && frame < 850
  })
  await mobilePage.screenshot({ path: screenshotPath('mobile-hud-touch.png') })
  await mobilePage.getByRole('button', { name: 'Open sound preferences', exact: true }).tap()
  await mobilePage.getByRole('dialog', { name: 'Settings', exact: true }).waitFor()
  await mobilePage.getByRole('button', { name: 'Close sound preferences', exact: true }).tap()
  await mobilePage.getByRole('dialog').waitFor({ state: 'detached' })
  for (const level of [3, 2, 4, 1]) {
    console.log(`VERIFY mobile return cancellation: level ${level}`)
    await mobilePage.getByRole('button', { name: 'Choose a floor', exact: true }).tap()
    await mobilePage.waitForSelector('.city-stage[data-elevator-loaded=true][data-interactive=true]', { timeout: 90000 })
    const floor = mobilePage.getByRole('button', { name: new RegExp(`^Select level ${level}:`) })
    await floor.focus();await floor.press('Enter')
    await mobilePage.waitForSelector('.city-stage[data-elevator-status=arrived][data-room-loaded=true]', { timeout: 90000 })
    const room = await mobilePage.locator('.city-stage').getAttribute('data-room')
    const hideMenu = mobilePage.getByRole('button', { name: 'Hide menu', exact: true })
    if (await hideMenu.isVisible()) await hideMenu.tap()
    await mobilePage.locator('#city').focus();await mobilePage.keyboard.press('Home')
    await touchSession.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 150, y: 350 }] })
    await touchSession.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 150, y: 450 }] })
    await touchSession.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await mobilePage.getByRole('dialog', { name: 'Return to elevator?' }).waitFor()
    // Let the swipe's compatibility-event sequence settle before the next tap.
    await mobilePage.waitForTimeout(350)
    await mobilePage.getByRole('button', { name: 'Stay in room', exact: true }).click()
    await mobilePage.screenshot({ path: screenshotPath(`mobile-stay-level-${level}.png`) })
    await mobilePage.getByRole('dialog', { name: 'Return to elevator?' }).waitFor({ state: 'detached' })
    await mobilePage.waitForTimeout(1000)
    for (const [x, y] of [[60, 160], [155, 200], [260, 170]]) {
      assert.ok(x !== undefined && y !== undefined)
      await mobilePage.touchscreen.tap(x, y)
      await mobilePage.waitForTimeout(100)
      assert.equal(await mobilePage.locator('.city-stage').getAttribute('data-elevator-status'), 'arrived', `Level ${level}: tapping the room after cancelling must not activate the elevator`)
      assert.equal(await mobilePage.locator('.city-stage').getAttribute('data-room'), room)
    }
    // The real doorway must remain usable from inside the room, rather than
    // disabling the exit entirely to avoid the cancelled-return regression.
    if (level === 3) {
      await mobilePage.locator('#room-progress').evaluate(input => {
        Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')!.set!.call(input, '2')
        input.dispatchEvent(new Event('input', { bubbles: true }));input.dispatchEvent(new Event('change', { bubbles: true }))
      })
      await mobilePage.waitForFunction(() => Math.abs(Number(document.querySelector<HTMLElement>('.city-stage')?.dataset.roomY) - 2) < .02)
      for (let turn = 0; turn < 4; turn++) {
        await touchSession.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 280, y: 200 }] })
        await touchSession.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 20, y: 200 }] })
        await touchSession.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
      }
      await mobilePage.waitForTimeout(350)
      await mobilePage.touchscreen.tap(156, 339)
      await mobilePage.waitForSelector('.city-stage[data-elevator-status=idle]', { timeout: 90000 })
      continue
    }
    // Cancellation must leave navigation working, including a deliberate retry.
    await mobilePage.keyboard.press('Escape')
    await mobilePage.locator('#city').focus();await mobilePage.keyboard.press('Home');await mobilePage.keyboard.press('PageUp')
    await mobilePage.getByRole('dialog', { name: 'Return to elevator?' }).waitFor()
    await mobilePage.getByRole('button', { name: 'Yes, return to elevator', exact: true }).tap()
    await mobilePage.waitForSelector('.city-stage[data-elevator-status=idle]', { timeout: 90000 })
  }
  await mobileContext.close()
  assert.deepEqual(errors, [])
  await context.close()
  console.log('PASS sound choice/preferences: initial YES/MUTED prompt, saved decisions, blocked-policy readiness, silent tooltips, mobile continuous slider/swipes, independent settings and modal focus')
} finally {
  await browser?.close()
  await new Promise(done => server.httpServer.close(done))
}
